apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
      version: blue
  template:
    metadata:
      labels:
        app: flask
        version: blue
    spec:
      containers:
        - name: flask
          image: sukanya996/blue:1
          ports:
            - containerPort: 5000
