apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask
    version: blue  # Initially set to blue version
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
